### ISSUE TITLE
[BUG] Resources not deployed with their service

### ISSUE THREAD

**Issue by fdziedzinl** [qoretechnologies/qorus-vscode#583] opened 2020-06-18 07:42 UTC
When deploying a service with "resource" via the UI, I get the following error:
`Files to deploy:
    04_advanced_examples/04_rest_server_service_with_swagger/AdvExampleRestServer-1.0.qsd
    04_advanced_examples/04_rest_server_service_with_swagger/AdvExampleRestServer-1.0.qsd.yaml

Deployment to main local Qorus instance - https://localhost:8011 has started ...
options: {"allow-redef":false,"force":false,"validate":true,"reload":true,"verbosity-level":1}
  ... response: {"id":238,"href":"api/latest/development/deploy/238"}
uri https://localhost:8011/api/latest/development/deploy/238
1s   checking deployment progress (ID: 238) ... 
... USER service AdvExampleRestServer:1.0 (26) remote: True autostart: True: updating
, status: FAILED
... ERROR: resource (N) "example.yaml" cannot be found as "/export/home/fdziedzinl/omq/user/04_advanced_examples/04_rest_server_service_with_swagger/example.yaml": READONLYFILE-OPEN-ERROR: cannot open '/export/home/fdziedzinl/omq/user/04_advanced_examples/04_rest_server_service_with_swagger/example.yaml': No such file or directory
, status: FAILED
Deployment failed (ID: 238)`

Meaning the resource was not deployed with it.

You can use the code in Training/04_advanced_examples/04_rest_server_service_with_swagger to test this.

**Comment by martin-zemek** [comment] 2020-06-25 14:45
The issue is fixed now; however, the service in this example fails to oload since Qorus seems to expect that each yaml file must be an interface metadata file and refuses to include the resource file `example.yaml`. Which is a Qorus issue.

**Closed by martin-zemek** 2020-06-25 14:45 UTC
Labels: bug
