### ISSUE TITLE
[BUG] different objects with the same name confuse the IDE

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#327] opened 2020-02-09 08:43 UTC
ex:
- two services with the name `test` are in different directories - only one service is shown in the hierarchy view
- two objects of different types, for example a service and a mapper code object, have the same name - in this case the code lens in the service will show `edit mapper code` instead of `edit service`

**Comment by turlyalz** [comment] 2020-03-12 09:33
duplicate of #269

**Closed by turlyalz** 2020-03-12 09:33 UTC
Labels: backend, bug, duplicate
