### ISSUE TITLE
missing class imports for java code

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#94] opened 2019-10-08 11:58 UTC
when generating java code - it's needed to include at least some basic classes:

`import com.qoretechnologies.qorus.OMQ;`
`import com.qoretechnologies.qorus.UserApi;`

And also the base class should be included if it's in qorus, e.g:
`import com.qoretechnologies.qorus.workflow.QorusWorkflow;`

For steps:
`import com.qoretechnologies.qorus.workflow.WorkflowApi;`
`import com.qoretechnologies.qorus.workflow.QorusNormalArrayStep;`

**Comment by omusil24** [comment] 2020-01-15 09:06
duplicate of #206

**Closed by omusil24** 2020-01-15 09:06 UTC
Labels: backend, bug
