### ISSUE TITLE
implement user documentation for the IDE

### ISSUE THREAD

**Issue by sejvlond** [qoretechnologies/qorus-vscode#64] opened 2019-03-06 13:10 UTC
add a documentation for release management and all other features

extend the README and thus a page on vscode marketplace and vscode extension page with info how to do a release

put somewhere a note, that CI/CD is the prefered way!

**Comment by omusil24** [comment] 2020-03-10 03:30
duplicate of #311

**Closed by omusil24** 2020-03-10 03:30 UTC
Labels: documentation
