### ISSUE TITLE
[BUG] after clicking on cancel button on login page the instance remains active

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#149] opened 2019-10-25 12:56 UTC
After clicking on cancel button on login page the instance remains active.

**Comment by Foxhoundn** [comment] 2019-10-28 11:54
Was this related to no_auth issue? I cannot reproduce this, because the instance should not be activated unless you actually submit the login.

**Comment by turlyalz** [comment] 2019-10-29 07:20
no, it's happening now, you can test it on rippy

**Comment by Foxhoundn** [comment] 2019-10-29 11:21
Ok, this should be fixed now.

**Closed by Foxhoundn** 2019-10-29 11:21 UTC
Labels: backend, bug, frontend
